// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc666.TestRobotBuilder;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSubsystemleftFront;
    public static SpeedController driveTrainSubsystemleftRear;
    public static SpeedController driveTrainSubsystemrightFront;
    public static SpeedController driveTrainSubsystemrightRear;
    public static RobotDrive driveTrainSubsystemRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSubsystemleftFront = new Jaguar(1, 1);
	LiveWindow.addActuator("DriveTrainSubsystem", "leftFront", (Jaguar) driveTrainSubsystemleftFront);
        
        driveTrainSubsystemleftRear = new Jaguar(1, 5);
	LiveWindow.addActuator("DriveTrainSubsystem", "leftRear", (Jaguar) driveTrainSubsystemleftRear);
        
        driveTrainSubsystemrightFront = new Jaguar(1, 6);
	LiveWindow.addActuator("DriveTrainSubsystem", "rightFront", (Jaguar) driveTrainSubsystemrightFront);
        
        driveTrainSubsystemrightRear = new Jaguar(1, 7);
	LiveWindow.addActuator("DriveTrainSubsystem", "rightRear", (Jaguar) driveTrainSubsystemrightRear);
        
        driveTrainSubsystemRobotDrive = new RobotDrive(driveTrainSubsystemleftFront, driveTrainSubsystemleftRear,
              driveTrainSubsystemrightFront, driveTrainSubsystemrightRear);
	
        driveTrainSubsystemRobotDrive.setSafetyEnabled(true);
        driveTrainSubsystemRobotDrive.setExpiration(0.1);
        driveTrainSubsystemRobotDrive.setSensitivity(0.5);
        driveTrainSubsystemRobotDrive.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
